### ISSUE TITLE
Use git log instead of temporary file

### ISSUE THREAD

**Issue by felixwellen** [adeel/instiki2git#3]
With the changes from #2, the ```updated_at```-time of the last committed revision is kept in a temporary file. It is possible, that different revisions have the same ```updated_at```-time and it is possible, that the ```updated_at```-time of a revision changes. The latter could currently lead to a revision getting committed multiple times in different stages.

We should use the git log instead of the file to determine which revisions need to be committed.

Suggestion from @sattlerc:
Both the `revisions` table and git commits store time with second resolution. So we could handle [the case of instiki2git stopping after committing some but not all revision in a group of revisions with the same ```updated_at```] by ordering commits with same `updated_at` time according to their revision id. That is, using the lexicographic ordering on (`updated_at`, `id`).

_Originally posted by @sattlerc in https://github.com/ncatlab/instiki2git/issues/2#issuecomment-1277711392_

**Comment by sattlerc** [comment]
> The latter could currently lead to a revision getting committed multiple times in different stages.

I do not see how to avoid this in principle. But commiting only revisions with `updated_at` at most one hour ago should make this extremely unlikely.

**Comment by felixwellen** [comment]
Do we want to avoid it?
I don't see a problem with having multiple commits for one revision. I would say this just means the history of the repo has a "higher resolution" as the history of the nlab.

**Comment by sattlerc** [comment]
Right, that's not bad.

Another scenario is that a revision gets updated within the same second. But with a safety interval it is extremely unlikely that we will only catch the first update.

**Comment by sattlerc** [comment]
I'll have a go at it.
